sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: o3ir64UXWtn7vEDfkGn9SzYniE2IL+3hJaaZWbW8ZFuK6UGs7Yd0ITbR16fTVL/OiOmt9VBRPcWo3aBHCjQGWJ2WhFzqT5ixLR8fm+nAR2B1KUPsHnDGLEzRZ1Ht45DOi6wXyUkvE21Xqxyf8TAJ9qvJXeaNgb5kB0UDKU0BrrQziXwOh0TKUEKbIvS0f62Ya5sw3FXRLl3xv1G/p/QcT3fsm7HTUgxPOkpGJcGCOyiJebIxK6g+LVMClowKR53tgnw/lWtWJj7I7lluPHDWBVLdLHG1sv6zPxwBe5+tyKj6MEXmoDYRuEzxJXvBeXyWd5aSyMrTauBO/K5hAkyQf3U+9CK1NIBhxz6/2SELV3s8d83c6HsRWKqmqSFc8WdTpuI17Lx+baLbSqgRNG5eTfKr3uCHvrY0yGC26eV/GCq4DytMnT4o+irWLZccCISNJu/qcwJ09WkCzHKIihVMFHhtKb5q8XevI60ELUXrtgSjuwI0t1IEY9N7Qro/D9+wtF9WUQC+nBu/mB5e++zWC5IqZw8H8UTEu7s8PyImd13JOlDVp88MdHMqJlzADRl3TFHUwB41x+tQcsbZibcXGTGurapL46RevNQdf6SIzpVdU1b28CPRnyXhIeknUvgeQTcuQy9LM43F+CupfquK+3/4kDXc0QjjIKbepn7KVoU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Essays-of-Michel-de-Montaigne---Volume-07_3587
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy